- name: Build & Deploy Docker Container
  hosts: webserver
  gather_facts: true
  become: true
  tasks:
   yum:
    name: nginx
    state: latest
          
   service:
     name: nginx
     start: started